filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.image: "elastic-app"
          config:
            - type: container
              paths:
                - "/var/lib/docker/containers/*/*.log"

output.elasticsearch:
  hosts: ["http://10.2.114.76:9200"]
  username: "elastic"
  password: "changeme"

processors:
  - add_docker_metadata: ~
  - decode_json_fields:
      fields: ["message"]
      process_array: false
      max_depth: 1
      target: ""
